version: "3.8"
services:
  db:
    image: "mariadb"
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_ALLOW_EMPTY_PASSWORD=""
      - MYSQL_RANDOM_ROOT_PASSWORD=""
      - MYSQL_INITDB_SKIP_TZINFO=""
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3306:3306
  php-apache:
    image: "php:7.4-apache"
    container_name: apache
    restart: always
    volumes:
      - ./sites:/var/www/html
    ports:
      - 80:80
  phpmyadmin:
    image: "phpmyadmin"
    container_name: myadmin
    environment:
      - PMA_HOST=db
    ports:
    - 8080:80





